### ISSUE TITLE
Gradle `bufBuild` hang on newer version of Protobuf

### ISSUE THREAD

**Issue by jeffawx** [bufbuild/buf-gradle-plugin#172]
The Gradle command hangs infinitely without any response: `./gradlew clean bufBuild --no-build-cache`

**This only happens after I upgraded protobuf-java from version `3.24.4` to `3.25.1`**

My project info:
- uses `protobuf-gradle-plugin` but no explicit workspace
- Only has `buf.yaml` with content:
```yaml
version: v1
breaking:
  use:
    - WIRE
  ignore:
    - google
lint:
  use:
    - DEFAULT
  except:
    - RPC_REQUEST_RESPONSE_UNIQUE
    - RPC_REQUEST_STANDARD_NAME
    - RPC_RESPONSE_STANDARD_NAME
``` 
- In gradle, buf is configured as:
```gradle
buf {
    publishSchema = true
}

```

Tried both plugin version `0.8.3` and newest `0.8.6`, as long as I upgraded project Protobuf version it started to hang.
